# Generated by Django 4.0 on 2021-12-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-classid', '-created_at']},
        ),
    ]
