# Generated by Django 4.0 on 2022-01-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_room_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
