# Generated by Django 4.0 on 2022-01-14 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='student',
            field=models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
