# Generated by Django 4.0 on 2022-01-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_room_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='classes.room'),
        ),
    ]
