# Generated by Django 4.0 on 2022-01-15 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0007_alter_content_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
