# Generated by Django 4.0 on 2022-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_room_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
